config = {
    'fps':2,
    'animation_fps':25,
    'width':1280,
    'height':720,
    'margin':60,
    'picture_width':400,
    'title_font_size': 48,
    'content_font_size': 28,
    'title_color':"#050505",
    'content_color':"#050505",
    'background_color':"#FFFFFF",
    'title_font': './util/SourceHanSansSC-Regular.otf',
    'content_font': './util/SourceHanSerifSC-Regular.otf',
    'logo_name': 'logo.png',
    'fade_duration':1,
    'test':False,
    'enable_logo':True,
    'skip_gif':False
}