config = {
    'fps':2,
    'animation_fps':25,
    'width':1920,
    'height':1080,
    'margin':60,
    'picture_width':400,
    'title_font_size': 53,
    'content_font_size': 36,
    'title_color':"#050505",
    'content_color':"#050505",
    'gcores_title_color': (255,255,255,246),
    'gcores_content_color': (255,255,255,205),
    'background_color':"#FFFFFF",
    'title_font': './util/PingFang-Heavy.ttf',
    'content_font': './util/PingFang-Medium.ttf',
    'logo_name': 'logo.png',
    'gcores_logo_name': 'gcores.png',
    'gcores_qr_name': 'qr.png',
    'fade_duration':1,
    'test':False,
    'enable_logo':True,
    'skip_gif':False,
    'open_offset':0
}